/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pathfinder;

import java.net.URL;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author grzala
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    private final ButtonGroup canvasMode;
    
    public MainFrame() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {}
        
        initComponents();
        
        canvasMode = new ButtonGroup();
        canvasMode.add(setStartButton);
        canvasMode.add(panButton);
        canvasMode.add(setGoalButton);
        
        canvas.setMode(Canvas.Mode.PAN);
        
        URL iconURL = getClass().getResource("/resources/icon.png");
        ImageIcon icon = new ImageIcon(iconURL);
        setIconImage(icon.getImage());
        
        canvas.requestFocus(true);
    }
    
    public Canvas getCanvas() {
        return canvas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        choicePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pathAlgorithmChooser = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel2 = new javax.swing.JLabel();
        graphAlgorithmChooser = new javax.swing.JComboBox<>();
        buttonPanel = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        fileChooseButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        panButton = new javax.swing.JToggleButton();
        setStartButton = new javax.swing.JToggleButton();
        setGoalButton = new javax.swing.JToggleButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
        searchButton = new javax.swing.JButton();
        canvasPanel = new javax.swing.JPanel();
        canvas = new pathfinder.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PathFinder");
        setFocusable(false);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(500, 200));
        setName("MainFrame"); // NOI18N
        setSize(new java.awt.Dimension(640, 480));

        controlPanel.setLayout(new javax.swing.BoxLayout(controlPanel, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Pathfinding Algorithm");
        choicePanel.add(jLabel1);

        pathAlgorithmChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A*", "Dijkstra" }));
        choicePanel.add(pathAlgorithmChooser);
        choicePanel.add(filler3);

        jLabel2.setText("Graph search algorithm");
        choicePanel.add(jLabel2);

        graphAlgorithmChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Closest Neighbour", "Brute Force", "MST Kruskal" }));
        graphAlgorithmChooser.setFocusable(false);
        choicePanel.add(graphAlgorithmChooser);

        controlPanel.add(choicePanel);

        clearButton.setText("clear");
        clearButton.setFocusPainted(false);
        buttonPanel.add(clearButton);

        fileChooseButton.setText("File");
        fileChooseButton.setActionCommand("filechoose");
        fileChooseButton.setFocusPainted(false);
        buttonPanel.add(fileChooseButton);
        buttonPanel.add(filler1);

        panButton.setSelected(true);
        panButton.setText("pan");
        panButton.setFocusPainted(false);
        buttonPanel.add(panButton);

        setStartButton.setText("set start");
        setStartButton.setFocusPainted(false);
        buttonPanel.add(setStartButton);

        setGoalButton.setText("set goal");
        setGoalButton.setFocusPainted(false);
        buttonPanel.add(setGoalButton);
        buttonPanel.add(filler2);

        searchButton.setFocusPainted(false);
        searchButton.setLabel("GO!");
        buttonPanel.add(searchButton);

        controlPanel.add(buttonPanel);

        getContentPane().add(controlPanel, java.awt.BorderLayout.PAGE_START);

        canvasPanel.setLayout(new javax.swing.BoxLayout(canvasPanel, javax.swing.BoxLayout.LINE_AXIS));

        canvas.setPreferredSize(new java.awt.Dimension(640, 450));

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        canvasPanel.add(canvas);

        getContentPane().add(canvasPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void createAndShowGUI() {
        setVisible(true);
        setLocation(100, 100);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private pathfinder.Canvas canvas;
    private javax.swing.JPanel canvasPanel;
    private javax.swing.JPanel choicePanel;
    public javax.swing.JButton clearButton;
    private javax.swing.JPanel controlPanel;
    public javax.swing.JButton fileChooseButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    public javax.swing.JComboBox<String> graphAlgorithmChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JToggleButton panButton;
    public javax.swing.JComboBox<String> pathAlgorithmChooser;
    public javax.swing.JButton searchButton;
    public javax.swing.JToggleButton setGoalButton;
    public javax.swing.JToggleButton setStartButton;
    // End of variables declaration//GEN-END:variables
}
