/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pathfinder;

import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author grzala
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private final Navigator n;
    
    private final ButtonGroup canvasMode;
    
    public MainFrame(Navigator n) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {}
        
        initComponents();
        canvas.setNavigator(n);
        this.n = n;
        
        canvasMode = new ButtonGroup();
        canvasMode.add(setStartButton);
        canvasMode.add(panButton);
        canvasMode.add(setGoalButton);
        
        canvas.setMode(Canvas.Mode.PAN);
        
        URL iconURL = getClass().getResource("/resources/icon.png");
        ImageIcon icon = new ImageIcon(iconURL);
        setIconImage(icon.getImage());
        
        canvas.requestFocus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        fileChooseButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        panButton = new javax.swing.JToggleButton();
        setStartButton = new javax.swing.JToggleButton();
        setGoalButton = new javax.swing.JToggleButton();
        choicePanel = new javax.swing.JPanel();
        graphAlgorithmChooser = new javax.swing.JComboBox<>();
        canvasPanel = new javax.swing.JPanel();
        canvas = new pathfinder.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PathFinder");
        setFocusable(false);
        setIconImages(null);
        setName("MainFrame"); // NOI18N

        controlPanel.setLayout(new javax.swing.BoxLayout(controlPanel, javax.swing.BoxLayout.Y_AXIS));

        clearButton.setText("clear");
        clearButton.setFocusPainted(false);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(clearButton);

        fileChooseButton.setText("File");
        fileChooseButton.setActionCommand("filechoose");
        fileChooseButton.setFocusPainted(false);
        fileChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(fileChooseButton);

        searchButton.setText("search");
        searchButton.setFocusPainted(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(searchButton);

        panButton.setSelected(true);
        panButton.setText("pan");
        panButton.setFocusPainted(false);
        panButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(panButton);

        setStartButton.setText("set start");
        setStartButton.setFocusPainted(false);
        setStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setStartButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(setStartButton);

        setGoalButton.setText("set goal");
        setGoalButton.setFocusPainted(false);
        setGoalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setGoalButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(setGoalButton);

        controlPanel.add(buttonPanel);

        graphAlgorithmChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Closest Neighbour", "Brute Force" }));
        graphAlgorithmChooser.setFocusable(false);

        javax.swing.GroupLayout choicePanelLayout = new javax.swing.GroupLayout(choicePanel);
        choicePanel.setLayout(choicePanelLayout);
        choicePanelLayout.setHorizontalGroup(
            choicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, choicePanelLayout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(graphAlgorithmChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        choicePanelLayout.setVerticalGroup(
            choicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, choicePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(graphAlgorithmChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        controlPanel.add(choicePanel);

        getContentPane().add(controlPanel, java.awt.BorderLayout.PAGE_START);

        canvasPanel.setLayout(new javax.swing.BoxLayout(canvasPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        canvasPanel.add(canvas);

        getContentPane().add(canvasPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        n.clear();
        canvas.repaint();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void fileChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseButtonActionPerformed
        JFileChooser chooser = new JFileChooser(".");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & PNG Images", "jpg", "png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
           n.setImage(chooser.getSelectedFile().getPath());
           canvas.setImage(chooser.getSelectedFile().getPath());
        }
        
        n.clear();
    }//GEN-LAST:event_fileChooseButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String graphAlgorithm = String.valueOf(graphAlgorithmChooser.getSelectedItem());
        n.setGraphAlgorithm(graphAlgorithm);
        n.performSearch();
        canvas.repaint();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void panButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panButtonActionPerformed
        canvas.setMode(Canvas.Mode.PAN);
    }//GEN-LAST:event_panButtonActionPerformed

    private void setStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setStartButtonActionPerformed
        canvas.setMode(Canvas.Mode.SETSTART);
    }//GEN-LAST:event_setStartButtonActionPerformed

    private void setGoalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setGoalButtonActionPerformed
        canvas.setMode(Canvas.Mode.SETGOAL);
    }//GEN-LAST:event_setGoalButtonActionPerformed

    public void createAndShowGUI() {
        setVisible(true);
        setLocation(100, 100);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private pathfinder.Canvas canvas;
    private javax.swing.JPanel canvasPanel;
    private javax.swing.JPanel choicePanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton fileChooseButton;
    private javax.swing.JComboBox<String> graphAlgorithmChooser;
    private javax.swing.JToggleButton panButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JToggleButton setGoalButton;
    private javax.swing.JToggleButton setStartButton;
    // End of variables declaration//GEN-END:variables
}
