/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pathfinder;

import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class MapChooser extends JDialog {
    /**
     * Creates new form MapChooser
     */
    
    private BufferedImage img;
    private int returnVal;
    
    public static final int CHOOSE = 1;
    public static final int CANCEL = 2;
    public static final int CUSTOM = 3;
    
    public MapChooser(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        
        this.setLocation(parent.getLocation().x + this.getSize().width/2, parent.getLocation().y + this.getSize().height/2);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapGroup = new javax.swing.ButtonGroup();
        choicePanel = new javax.swing.JPanel();
        upperChoicesPanel = new javax.swing.JPanel();
        bigMazeRadioButton = new javax.swing.JRadioButton();
        circleMazeRadioButton = new javax.swing.JRadioButton();
        obstaclesRadioButton = new javax.swing.JRadioButton();
        lowerChoicesPanel = new javax.swing.JPanel();
        customMapRadioButton = new javax.swing.JRadioButton();
        noMapRadioButton = new javax.swing.JRadioButton();
        labelPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        optionPanel = new javax.swing.JPanel();
        chooseButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(20, 32767));
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Map");
        setMinimumSize(new java.awt.Dimension(300, 123));
        setResizable(false);

        choicePanel.setLayout(new java.awt.GridLayout(0, 1));

        mapGroup.add(bigMazeRadioButton);
        bigMazeRadioButton.setSelected(true);
        bigMazeRadioButton.setText("Big maze");
        upperChoicesPanel.add(bigMazeRadioButton);

        mapGroup.add(circleMazeRadioButton);
        circleMazeRadioButton.setText("Circle maze");
        upperChoicesPanel.add(circleMazeRadioButton);

        mapGroup.add(obstaclesRadioButton);
        obstaclesRadioButton.setText("Obstacles");
        upperChoicesPanel.add(obstaclesRadioButton);

        choicePanel.add(upperChoicesPanel);

        mapGroup.add(customMapRadioButton);
        customMapRadioButton.setText("Custom map");
        lowerChoicesPanel.add(customMapRadioButton);

        mapGroup.add(noMapRadioButton);
        noMapRadioButton.setText("No Map");
        lowerChoicesPanel.add(noMapRadioButton);

        choicePanel.add(lowerChoicesPanel);

        getContentPane().add(choicePanel, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Choose Map:");
        labelPanel.add(jLabel1);

        getContentPane().add(labelPanel, java.awt.BorderLayout.PAGE_START);

        chooseButton.setText("Choose");
        chooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseButtonActionPerformed(evt);
            }
        });
        optionPanel.add(chooseButton);
        optionPanel.add(filler1);

        cancelButton.setText("Cancel ");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        optionPanel.add(cancelButton);

        getContentPane().add(optionPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseButtonActionPerformed
        setVisible(false);
        
        String name = null;
        if (bigMazeRadioButton.isSelected()) {
            name = "bigmaze.jpg";
        } else if (circleMazeRadioButton.isSelected()) {
            name = "circlemaze.jpg";
        } else if (obstaclesRadioButton.isSelected()) {
            name = "obstacles.jpg";
        } else if (customMapRadioButton.isSelected()) {
            returnVal = CHOOSE;
            JFileChooser chooser = new JFileChooser(".");
            FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & PNG Images", "jpg", "png");
            chooser.setFileFilter(filter);
            int returnVal = chooser.showOpenDialog(null);
            try {
                if(returnVal == JFileChooser.APPROVE_OPTION) 
                    img = ImageIO.read(chooser.getSelectedFile());
            } catch(IOException e) {
                img = null;
            }
            close();
            return;
        } else if (noMapRadioButton.isSelected()) {
            returnVal = CHOOSE;
            img = null;
            close();
            return;
        }
        
        try {
            if (name == null || name.equals("")) throw new IOException();
            img = ImageIO.read(getClass().getResource("/resources/" + name));
        } catch (IOException e) {
            img = null;
        }
        
        returnVal = CHOOSE;
        close();
    }//GEN-LAST:event_chooseButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        returnVal = CANCEL;
        close();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void close() {
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }
    
    public BufferedImage getChoice() {
        return img;
    }
    
    public int returnVal() {
        return returnVal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bigMazeRadioButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel choicePanel;
    private javax.swing.JButton chooseButton;
    private javax.swing.JRadioButton circleMazeRadioButton;
    private javax.swing.JRadioButton customMapRadioButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JPanel lowerChoicesPanel;
    private javax.swing.ButtonGroup mapGroup;
    private javax.swing.JRadioButton noMapRadioButton;
    private javax.swing.JRadioButton obstaclesRadioButton;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel upperChoicesPanel;
    // End of variables declaration//GEN-END:variables
}
