/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pathfinder;

import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author grzala
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private final Navigator n;
    
    private final ButtonGroup canvasMode;
    
    public MainFrame(Navigator n) {
        initComponents();
        canvas.setNavigator(n);
        this.n = n;
        
        
        canvasMode = new ButtonGroup();
        canvasMode.add(setStartButton);
        canvasMode.add(panButton);
        canvasMode.add(setGoalButton);
        
        canvas.setMode(Canvas.Mode.PAN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        fileChooseButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        panButton = new javax.swing.JToggleButton();
        setStartButton = new javax.swing.JToggleButton();
        setGoalButton = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        canvas = new pathfinder.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PathFInder");
        setFocusable(false);
        setName("MainFrame"); // NOI18N

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel3.add(clearButton);

        fileChooseButton.setText("File");
        fileChooseButton.setActionCommand("filechoose");
        fileChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseButtonActionPerformed(evt);
            }
        });
        jPanel3.add(fileChooseButton);

        searchButton.setText("search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel3.add(searchButton);

        panButton.setSelected(true);
        panButton.setText("pan");
        panButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panButtonActionPerformed(evt);
            }
        });
        jPanel3.add(panButton);

        setStartButton.setText("set start");
        setStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setStartButtonActionPerformed(evt);
            }
        });
        jPanel3.add(setStartButton);

        setGoalButton.setText("set goal");
        setGoalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setGoalButtonActionPerformed(evt);
            }
        });
        jPanel3.add(setGoalButton);

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel2.add(canvas);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        n.clearGoals();
        canvas.repaint();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void fileChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & PNG Images", "jpg", "png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
           n.setImage(chooser.getSelectedFile().getPath());
           canvas.setImage(chooser.getSelectedFile().getPath());
        }
        
    }//GEN-LAST:event_fileChooseButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        n.performSearch();
        canvas.repaint();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void panButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panButtonActionPerformed
        canvas.setMode(Canvas.Mode.PAN);
    }//GEN-LAST:event_panButtonActionPerformed

    private void setStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setStartButtonActionPerformed
        canvas.setMode(Canvas.Mode.SETSTART);
    }//GEN-LAST:event_setStartButtonActionPerformed

    private void setGoalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setGoalButtonActionPerformed
        canvas.setMode(Canvas.Mode.SETGOAL);
    }//GEN-LAST:event_setGoalButtonActionPerformed

    public void createAndShowGUI() {
        setVisible(true);
        setLocation(100, 100);
    }

    
    public void paintLoop() {
        while (true) {
            try {
                canvas.repaint();
                Thread.sleep(10);
            } catch(InterruptedException e) {
            }
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pathfinder.Canvas canvas;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton fileChooseButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton panButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JToggleButton setGoalButton;
    private javax.swing.JToggleButton setStartButton;
    // End of variables declaration//GEN-END:variables
}
